### ISSUE TITLE
Starting Clojure-Party-REPL fails

### ISSUE THREAD

**Issue by peter-lyons-kehl** [party-repl/clojure-repl#12]
Dear Hans and Tomomi,

Please help.
Steps:
1. Create a new, empty lein project, by `lein new party-test`
lein --version
Leiningen 2.8.1 on Java 1.8.0_192 OpenJDK 64-Bit Server VM
clj
*clojure-version*
{:major 1, :minor 10, :incremental 0, :qualifier "beta3"}
2. In Party-REPL settings I set path to lein. When starting Party-REPL:

**Atom**: 1.32.2 x64
**Electron**: 2.0.12
**OS**: "Manjaro Linux"
**Thrown From**: [clojure-party-repl](https://github.com/party-repl/clojure-party-repl) package 1.1.0

### Stack Trace

Uncaught Error: spawn ENOTDIR

```
At internal/child_process.js:323

Error: spawn ENOTDIR
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn (child_process.js:514:9)
    at /packages/clojure-party-repl/lib/clojure-party-repl.js:4242:159)
    at Object.clojure_party_repl.local_repl.start_repl_process (/packages/clojure-party-repl/lib/clojure-party-repl.js:4240:375)
    at Object.clojure_party_repl.local_repl.start_local_repl (/packages/clojure-party-repl/lib/clojure-party-repl.js:4246:284)
    at HTMLElement.clojure_party_repl.core.start_local_repl (/packages/clojure-party-repl/lib/clojure-party-repl.js:4739:424)
    at CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:384:43)
    at Object.didConfirmSelection (/usr/lib/atom/node_modules/command-palette/lib/command-palette-view.js:152:29)
    at SelectListView.confirmSelection (/usr/lib/atom/node_modules/atom-select-list/src/select-list-view.js:400:20)
    at SelectListView.didClickItem (/usr/lib/atom/node_modules/atom-select-list/src/select-list-view.js:286:10)
    at ListItemView.onclick (/usr/lib/atom/node_modules/atom-select-list/src/select-list-view.js:221:31)
    at ListItemView.didClick (/usr/lib/atom/node_modules/atom-select-list/src/select-list-view.js:448:10)
```

### Commands

```
     -4:26 command-palette:toggle (div.tool-panel.tree-view)
 16x -4:20.6.0 core:move-down (input.hidden-input)
     -4:15.7.0 core:move-up (input.hidden-input)
     -4:14.8.0 core:confirm (input.hidden-input)
     -4:14.8.0 tree-view:remove-project-folder (div.tool-panel.tree-view)
     -4:00.4.0 command-palette:toggle (input.hidden-input)
     -3:47.7.0 core:select-all (input.hidden-input)
  3x -3:39.2.0 core:backspace (input.hidden-input)
  2x -3:36.7.0 core:select-all (input.hidden-input)
     -3:15 settings-view:view-installed-packages (input.hidden-input)
     -1:56.2.0 command-palette:toggle (div.package-detail.panels-item)
     -1:52.1.0 clojure-party-repl:startLocalRepl (div.package-detail.panels-item)
     -1:39.5.0 command-palette:toggle (input.hidden-input)
     -1:35 clojure-party-repl:startLocalRepl (input.hidden-input)
     -0:09.5.0 command-palette:toggle (input.hidden-input)
     -0:05.9.0 clojure-party-repl:startLocalRepl (input.hidden-input)
```

### Non-Core Packages

```
clojure-party-repl 1.1.0 
```

**Comment by hitsusorisaku** [comment]
Hi Peter,

So sorry about the trouble, thanks for the very clear details, really appreciate it!

Hopefully, I can dive into the problem next week, I'll keep you posted. Thanks!

**Comment by peter-lyons-kehl** [comment]
Hi Tomomi,

If you'd like my Atom config files, and/or SSH access, I'll gladly give it to you.
Have a good week.

**Comment by vbsteja** [comment]
Hi, giving party repl a try on atom on windows, it fails to start throwing 
**Cannot start a REPL. Current file is not located inside a project directory or the project directory doesn't have project.clj file.**,
even though i am starting party repl from the project folder which contains project.clj file.  apologies if i am not aware of party repl work or not on windows.

**Comment by timxor** [comment]
If I recall, there was no support for windows. Did they add support?

**Comment by peter-lyons-kehl** [comment]
Hi Tim @tcsiwula,

The described problem happened on Manjaro Linux. I don't have Windows.
