### ISSUE TITLE
Uncaught Error: spawn ENOTDIR

### ISSUE THREAD

**Issue by Neiby** [party-repl/clojure-repl#14]
[Enter steps to reproduce:]

1. New installation of clojure. Tried to enable local lein REPL. Most likely I don't have something set correctly.

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.3
**Thrown From**: [clojure-party-repl](https://github.com/party-repl/clojure-party-repl) package 1.1.0

### Stack Trace

Uncaught Error: spawn ENOTDIR

```
At internal/child_process.js:358

Error: spawn ENOTDIR
    at ChildProcess.spawn (internal/child_process.js:358:11)
    at Object.spawn (child_process.js:543:9)
    at /packages/clojure-party-repl/lib/clojure-party-repl.js:4242:159)
    at Object.clojure_party_repl.local_repl.start_repl_process (/packages/clojure-party-repl/lib/clojure-party-repl.js:4240:375)
    at Object.clojure_party_repl.local_repl.start_local_repl (/packages/clojure-party-repl/lib/clojure-party-repl.js:4246:284)
    at HTMLElement.clojure_party_repl.core.start_local_repl (/packages/clojure-party-repl/lib/clojure-party-repl.js:4739:424)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349290)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:347765)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:725694)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:733617)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
     -8:08.5.0 core:paste (input.hidden-input)
     -1:04.0 clojure-party-repl:startLocalRepl (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 2.0.1 
clojure-party-repl 1.1.0 
intentions 1.1.5 
linter 2.3.1 
linter-clojure 1.2.0 
linter-ui-default 1.8.1 
```

**Comment by hitsusorisaku** [comment]
Hey John, thanks for reaching out!

Unfortunately I haven’t been able to work on and maintain the project for the past year, the issue could be caused by party-repl’s dependencies.

Here are some ideas:
- Maybe nrepl isn’t able to start because party-repl is not be able to locate the root of the project’s folder. The stack trace you showed might indicate this is the problem. Can you double check the project directory is correct?

- Which version of Clojure are you using? It’s possible that party-repl doesn’t support newer versions. If it’s feasible, please try with Clojure 1.7 or 1.8. As I recall, there might also be an incompatibility with the newer nrepl library which changed the message format. 

Let me know if you find any solutions or have more information on this issue. l would be happy to take a PR if possible.
